### ISSUE TITLE
specan and ui works but scan or util = Unable to find hci0 (-1)

### ISSUE THREAD

**Issue by ad5qa** [greatscottgadgets/ubertooth#133]
I have installed ubertooth build following the instructions. When I use the ubertooth-specan and ubertooth-specan-ui works however when I use ubertooth-scan none of the options work and display "error Unable to find hci0 (-1)". 

hcitool dev
Devices:

Any suggestions? I am running Kali 2.0 and all the libraries seemed to compile and install without errors.

**Comment by mikeryan** [comment]
ubertooth-scan requires a normal Bluetooth device (e.g., builtin Bluetooth adapter, USB Bluetooth dongle). It looks like you don't have any Bluetooth devices in your Kali system. Either add a USB Bluetooth dongle, or if you're testing from a VM try sending your host's Bluetooth adapter into the VM system.

**Comment by ad5qa** [comment]
Thanks, I connected the Bluetooth USB and it worked, overlooked that one.

**Comment by liut12** [comment]
I am curious what did you do to make it work?

**Comment by dominicgs** [comment]
@liut12 I am unsure what you are asking.  This was a question rather than a bug.  The question was about tools that require a Bluetooth controller to be attached to the system.  The solution to make them work is, as Mike said, to attach a Bluetooth controller to the system.

If you are having a different problem, please open a new issue for it.
