### ISSUE TITLE
Question about UAP confidence and NAP discovery

### ISSUE THREAD

**Issue by maximcherny** [greatscottgadgets/ubertooth#142]
Hi,

This is not strictly an issue but rather some questions following on from:

http://ubertooth.blogspot.com.au/2014/06/discovering-bluetooth-uap.html

First: What did you have in mind with regards to "Another nice enhancement would be maintaining a confidence value for the current UAP (or perhaps for multiple candidates)." 

I'm interested in possibly adding something like as part of the research project that I am doing and would be keen to find out if you had any additional details around this.

Second: I note that the NAP address part (well, being insignificant) is being ignored when performing basic device pings and name and service discovery etc. Is there is a reliable way of checking for device presence that does not ignore the supplied NAP value?

Thanks in advance.

**Comment by dominicgs** [comment]
1) The process for finding the UAP and CLK relies timing between packets.  After we've found the UAP and CLK we continue to receive packets and if the UAP doesn't match we either have to drop the packet or drop the UAP.

This can get especially complicated when we are surveying multiple piconets.  In this instance it may be useful to keep a score / confidence value for the UAP, e.g. how many packets have we seen from that piconet?  If the score is high, then we can check for CLK being out of sync, if the score is low, maybe the UAP was a false positive.

2) The NAP is only used in two places: device discovery and encryption.  If you have the UAP+LAP and want to guess the NAP, it's likely that discovery isn't an option for you (otherwise you would have used it anyway).  Starting a connection and enabling encryption may be an option, but it's not going to be quick.

There may be other methods, but I can't think of any now.
