### ISSUE TITLE
[SERVER] uh oh, full_buf not emptied on Ubuntu 15.04

### ISSUE THREAD

**Issue by chawandi08** [greatscottgadgets/ubertooth#178]
I have installed packages (versions mentioned below), I flashed firmware on my ubertooth dongle & verified too. 

kismet-2013-03-R1b        
ubertooth-2015-10-R1
libbtbb-2015-10-R1        

I will be waiting for  data, but after sometime when I kill server this log will be thrown.

Could you let me know what I am doing wrong ?

[SERVER] uh oh, full_buf not emptied
[SERVER] uh oh, full_buf not emptied
[SERVER] uh oh, full_buf not emptied
[SERVER] uh oh, full_buf not emptied
[SERVER] uh oh, full_buf not emptied

**Comment by dominicgs** [comment]
This is a known issue which is caused by the host not keeping up with the data rate from USB.  There have been significant improvements to this part of the code in the past few months, so the next release should improve things.

If you want to try out these improvements, you can build and run libbtbb and ubertooth from git.

This issue is being tracked here: https://github.com/greatscottgadgets/ubertooth/issues/108
