### ISSUE TITLE
Kismet not capturing packets

### ISSUE THREAD

**Issue by munnashk** [greatscottgadgets/ubertooth#206]
Hi I have a Ubertooth One and i have installed all the required software and tools by following the link https://github.com/greatscottgadgets/ubertooth/wiki/Build-Guide in Kali linux 2.0 Virtual Box. 

I have kismet tool and was able to see the packets captures in pcapbtbb file.

after a day when i have started kismet and added a source and loaded the plugin but was unable to see any captures happening.

when i ran ubertooth-rx tool, i was able to see all the packets which will end with "uh oh, full_buf not emptied" but kismet did not capture any packet and displayed as "No Networks Seen'

and kismet server console with be filled with "uh oh, full_buf not emptied" 

Also kismet is creating an empty pcapdump files.

please look into attached screen grabs.

the ubertooth hardware has 4 leds ON i.e. rst, usb, 1v8, usr.

![kismet server console_1](https://cloud.githubusercontent.com/assets/7323323/15961264/722a3ca8-2f21-11e6-96ef-b882ceb75767.JPG)
![kismet server console_2](https://cloud.githubusercontent.com/assets/7323323/15961265/72300732-2f21-11e6-88d8-9088c301d720.JPG)
![capture](https://cloud.githubusercontent.com/assets/7323323/15961266/72317aae-2f21-11e6-8191-5e2f865a5544.JPG)

**Comment by gmcremona** [comment]
Same problem here! i tried multiple instalations on diferent machines(including VMs) and got the same result in all of them. Even i tried with diferent versions of kismet because i thought it was his fault, but didn't work either. I follow this guide: 
https://github.com/greatscottgadgets/ubertooth/wiki/Build-Guide 
and the third party software installation:
https://github.com/greatscottgadgets/ubertooth/wiki/Third-Party-Software 
Always on Ubuntu 15.04. I will try in kali linux now(the latest version) but i don't expect different results.
Is there a enviorment(OS, Ubertooth & libbtbb & kismet versions) that you recomend?

**Comment by dominicgs** [comment]
I recommend Ubuntu as a host OS for Ubertooth, but it should be running natively.  VMs do horrible things to our USB connection and this is very likely caused by using a VM.

**Comment by gmcremona** [comment]
It worked! i used a VM with the latest kali linux version. Anyway, what solve the problem was the latest versions of libbtbb and ubertooth in the master banches. Also the latest release of kismet(2016-10-R1 i believe).

I think that the issue "uh oh, full_buf not emptied" doesn't allow you to gather packets when the kismet is running. Since this problem is solved in the master branch of ubertooth, it fixes kismet problem too
