### ISSUE TITLE
qt5 support for ubertooth-specan

### ISSUE THREAD

**Issue by ZeroChaos-** [greatscottgadgets/ubertooth#308]
most distros are killing qt4, please update ubertooth-specan to qt5

**Comment by a17r** [comment]
Official Qt4 support ended in 2015.

**Comment by Etherealflux** [comment]
This caused me some grief when getting things installed - I have Python3 as default, so ubertooth was built and installed for it, but I could not get PySide to work (probably because qt4 is dead as a doornail at this point). I had to put a symlink on my path so that `python` resolved to `python2`, and then make/make install again to get `ubertooth-specan-ui` working.

A note in the build instructions about this would be helpful!

**Comment by ayleph** [comment]
I submited #336 to address this issue.

**Comment by dominicgs** [comment]
Fantastic, thank you for the contribution!

I've merged it.
