### ISSUE TITLE
lsusb - OpenMoko

### ISSUE THREAD

**Issue by Bushido0** [greatscottgadgets/ubertooth#339]
### Steps to reproduce
1.lsusb shows Bus 002 Device 024: ID 1d50:6002 OpenMoko, Inc. 
2.This is not a VM
3.Firmware updated properly, not sure why this is going on.

### Expected behaviour
Tell us what you expect should happen
Expected it to show ubertooth.

### Actual behaviour
Tell us what happens instead
Bus 002 Device 024: ID 1d50:6002 OpenMoko, Inc. 
### Version information
**Operating system**:
Kali Linux 2018
**Ubertooth tools version (ubertooth-rx -V):**
libubertooth 1.1 (2018-08-R1), libbtbb 1.0 (2018-06-R1)
**libbtbb version:**

**Ubertooth firmware version (ubertooth-util -v):**
Firmware version: 2018-08-R1 (API:1.05)

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by dominicgs** [comment]
This is expected, but I understand it's unusual.  The Open Moko project gave us the USB ID that we use and the `lsusb` too is based on an index of the IDs rather than the strings reported from the device.

`sudo lsusb -vd 1d50:6002` will report the strings from the firmware.

Also, `ubertooth-util -Vv` will show firmware information.
