### ISSUE TITLE
Ubertooth-rx "uh oh, full_buf not emptied"

### ISSUE THREAD

**Issue by joswr1ght** [greatscottgadgets/ubertooth#4]
After running "ubertooth-rx -l LAP" for several minutes and pressing "CTRL+C" to quit spits out endless "uh oh, full_buf not emptied" messages to the console.

Afterward, the Ubertooth One has to be removed and reinserted for use, otherwise a USB error is generated:

```
# ubertooth-rx
usb_claim_interface error -6
ubertooth-rx - passive Bluetooth discovery/decode
```

This is on Ubuntu 12.04, Ubertooth host and firmware code from git as of 2/3/14:

```
# ubertooth-util -v
Firmware revision: git-e3d85ca
```

**Comment by michaeljau** [comment]
I am also seeing the same message and behavior shortly after starting ubertooth-rx. I only saw 2 LAP messages the first time I ran ubertooth-rx and since then I only see "oh oh, fulll_buf not emptied" messages.
I am using a Ubuntu 14.04 virtual machine running on VMWare Player 6.x. I did increase the RAM (to 2GB) and processing resources (to 2 cores) and had the same issue.
(Reading threads though it sounds like people have had mixed success getting ubertooth to work with VMs).

**Comment by rubenmak** [comment]
I'm having the same "uh oh, full_buf not emptied" after updating to the latest firmware. I would like to flash my ubertooth back to the ubertooth-2012-10-R1 firmware, so I'm looking for the .dfu file. However, https://github.com/greatscottgadgets/ubertooth/releases/tag/2012-10-R1 only seems to give the source code (unlike the newer releases).

I probably should have used ubertooth-dfu -read first to make a backup of my firmware, like suggested by https://penturalabs.wordpress.com/2014/02/20/ubertooth-updated-for-2014/. Unfortunately I just read it after following the https://github.com/greatscottgadgets/ubertooth/wiki/Firmware. Since quite some people seem to have this problem and want to go back to the previous version, it might be useful to add making a backup to these instructions.

For me it would be of great help is someone could provide the .dfu file for the ubertooth-2012-10-R1 version.

**Comment by dominicgs** [comment]
Previous releases (and their binary firmware files) were hosted on SourceForge, which is unfortunately down right now.  Releases before 2014 on GitHub are automatically generated from the git tags, and therefore don't have binary firmware files.

The "uh oh, full_buf not emptied" error is caused by a bug in the host code rather than an issue in the firmware.  You will need to make sure you are using the 2012-10-R1 host code too.

I have uploaded a dfu file here: dominicspill.com/ubertooth/bluetooth_rxtx.2012-10-R1.dfu
